@ClimbEdge.API_HostAddress = http://localhost:5160

### 1. Endpoint raíz (sin autenticación)
GET {{ClimbEdge.API_HostAddress}}/api
Accept: application/json

###

### 2. Información de la API (sin autenticación)
GET {{ClimbEdge.API_HostAddress}}/api/info
Accept: application/json

###
