@startwbs Packages Diagram

* Entities
**_> Configurations
**_> UserProfile
**_> AppUser
**_> AppRole
** Boards
***_> BoardVisibility <<enum>>
***_> BoardMemberRole <<enum>>
***_> Board
***_> BoardMember
***_> BoardConfig
***_> BoardItemType
***_> BoardItemTextureMaterial
***_> BoardItemTexture
***_> BoardItem
*** Problems
****_> BoardProblem
****_> BoardProblemItem
****_> BoardProblemItemType
****_> BoardProblemAngle
****_> BoardProblemTag
** DifficultyScales
***_> DifficultyScaleType
***_> DifficultyScaleName
***_> DifficultyScale
***_> DifficultyGroup
** Mountains
*** Itinerary
****_> MountaineerTickType <<enum>>
** Climbing
***_> ClimbZone
***_> ClimbRoute
***_> ClimbTag
***_> RockFeatures
***_> ClimbRouteDescription
***_> ClimbRouteFile
***_> ClimbZoneFile
** Sessions
***_> UserSession
***_> UserSessionProgress
***_> ClimbTickType <<enum>>
***_> BoardSessionSummary
** Training
** Payment
** Notifications
** AI
***_> AIModel
***_> AIGenerationRequest
***_> AITrainingData
***_> AIModelLog

@endwbs